fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"

pidev:
    resource: "@PidevBundle/Resources/config/routing.yml"
    prefix:   /
fos_js_routing:
    resource: "@FOSJsRoutingBundle/Resources/config/routing/routing.xml"

ancarebeca_fullcalendar:
    resource: "@FullCalendarBundle/Resources/config/routing.yml"
app:
    resource: '@AppBundle/Controller/'
    type: annotation
mgilet_notifications:
    resource: "@MgiletNotificationBundle/Controller/"
    prefix: /notifications

