<?php
/**
 * Created by PhpStorm.
 * User: admin
 * Date: 27/3/2018
 * Time: 4:57 م
 */

namespace PidevBundle\Repository;
use Doctrine\DBAL\Connection;
use Doctrine\ORM\Query\AST\Functions\CurrentTimestampFunction;

/**
 * CommentaireRepository
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */

class CommentaireRepository extends \Doctrine\ORM\EntityRepository
{
    public function affichercomm($id_publication)
    {

        $q = $this->getEntityManager()
            ->createQuery("SELECT c FROM PidevBundle:CommentaireR c WHERE c.id_publication =:id_publication")
            ->setParameter('id_publication', $id_publication);
        return $q->getResult();

    }

    public function nombrec($id_publication)
    {
        $q = $this->getEntityManager()
            ->createQuery("SELECT c FROM PidevBundle:CommentaireR c WHERE c.id_publication =:id_publication")
            ->setParameter('id_publication', $id_publication);
        return $q->getResult();
    }

    public function deleteCommentaire($id1,$iduser)
    {
        $q = $this->getEntityManager()
            ->createQuery("Delete FROM PidevBundle:CommentaireR c WHERE c.id =:id1 AND c.iduser=:iduser")
            ->setParameter('id1', $id1)
            ->setParameter('iduser', $iduser);
        return $q->getResult();
    }

    public function updateCommentaire($objet, $datte, $id,$iduser)
    {    $q = $this->getEntityManager()
            ->createQuery("UPDATE PidevBundle:CommentaireR c SET c.objet=:objet,c.date=:datte WHERE c.id =:id AND c.iduser=:iduser")
        ->setParameter('objet',$objet)
        ->setParameter('datte',$datte)
        ->setParameter('id', $id)
        ->setParameter('iduser', $iduser);
        return $q->getResult();

    }
}