<?php
/**
 * Created by PhpStorm.
 * User: admin
 * Date: 4/4/2018
 * Time: 5:23 م
 */

namespace PidevBundle\Repository;
/**
 * ReponseCRepository
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */

class ReponseCRepository extends \Doctrine\ORM\EntityRepository
{
    public function afficherrep($id)
    {$q = $this->getEntityManager()
            ->createQuery("SELECT r FROM PidevBundle:ReponseC r WHERE r.id_commentaire =:id")
            ->setParameter('id', $id);
        return $q->getResult();

    }

    public function deleteReponse($id1,$iduser)
    {
        $q = $this->getEntityManager()
            ->createQuery("Delete FROM PidevBundle:ReponseC c WHERE c.id =:id1 AND c.id_user=:iduser")
            ->setParameter('id1', $id1)
            ->setParameter('iduser', $iduser);
        return $q->getResult();
    }
    public function updateReponse($contenu,$datte,$id,$iduser,$idcommentaire)
    {    $q = $this->getEntityManager()
        ->createQuery("UPDATE PidevBundle:ReponseC c SET c.contenu=:contenu,c.date=:datte WHERE c.id =:id AND c.id_user=:id_user AND c.id_commentaire=:idcommentaire")
        ->setParameter('contenut',$contenu)
        ->setParameter('datte',$datte)
        ->setParameter('id', $id)
        ->setParameter('iduser', $iduser)
        ->setParameter('idcommentaire', $idcommentaire);
        return $q->getResult();

    }


}