<?php
/**
 * Created by PhpStorm.
 * User: admin
 * Date: 26/3/2018
 * Time: 12:09 ص
 */

namespace PidevBundle\Repository;
/**
 * RubriqueRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */

class RubriqueRepository extends \Doctrine\ORM\EntityRepository
{    public function afficherRubriqueSanitaire(){

    $q=$this->getEntityManager()
        ->createQuery("SELECT r FROM PidevBundle:Rubrique_sanitaire r WHERE r.date =CURRENT_DATE()");
    return $q->getResult();

}


}