<?php
/**
 * Created by PhpStorm.
 * User: admin
 * Date: 22/3/2018
 * Time: 4:28 م
 */

namespace PidevBundle\Repository;
/**
 * UserRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */

class UserRepository extends \Doctrine\ORM\EntityRepository
{
    public function findfournisseur($field,$field1){

        $q=$this->getEntityManager()
            ->createQuery("SELECT u FROM PidevBundle:User u WHERE u.type_service = :field AND u.adresse = :field1")
            ->setParameter('field',$field)
            ->setParameter('field1',$field1);
        return $q->getResult();

    }



}